### ISSUE TITLE
Plugin works on linux but not on mac agents

### ISSUE THREAD

**Issue by yaron-idan** [JetBrains/teamcity-vmware-plugin#18]
When following the instructions for configuring the plugins I manage to get it working fine on Linux agents. However, when trying to set the same configurations on a mac agent the agent launches but stays unauthorized, while I was expecting it to be authorized automatically.
Is this a known issue of the plugin and mac agents?

===EDIT===
Investigating further reveals the following error message in the mac agent logs - 
https://github.com/JetBrains/teamcity-vmware-plugin/blob/ca02f89f42330be6826a4132d7ef7c6ffdd66d1c/cloud-vmware-agent/src/main/java/jetbrains/buildServer/clouds/vmware/VMWarePropertiesReader.java#L63

I'm getting this error despite having installed the latest version of vmware tools on the mac vm, and searching for the file (`/usr/sbin/vmware-rpctool`) reveals it is not anywhere on the machine. Is this some kind of inconsistency with the latest vmware-tools versions?

**Comment by paksv** [comment]
Latest builds for 9.x.x: https://teamcity.jetbrains.com/viewType.html?buildTypeId=TeamCityPluginsByJetBrains_TeamcityVmwarePlugin_Build

Issue in JB YT: https://youtrack.jetbrains.com/issue/TW-50103
