### ISSUE TITLE
Multiple Images per Cloud Profile

### ISSUE THREAD

**Issue by oryagel** [JetBrains/teamcity-vmware-plugin#21]
Hi,
I see that it's possible to add multiple images per cloud profile.
Let's say for example that I have an image with two snapshots, one with nodejs and another with python. I'm adding two images to the plugin, one for each snapshot.
How Teamcity will know which snapshot to start? 
I tried something similar and got weird behavior. It seems like the plugin uses the last added image and ignores the previous added image.
In addition, I can see the Compatible Configurations tab in the cloud profile, I would expect to see that tab for each image.

What am I missing?

Thanks

**Comment by paksv** [comment]
Hi, to be able to add the same image twice you need to provide "Custom image name" for them, so they would clone into VMs with different names.
https://confluence.jetbrains.com/display/TCD10/Setting+Up+TeamCity+for+VMware+vSphere+and+vCenter#SettingUpTeamCityforVMwarevSphereandvCenter-NotesonconfiguringAgentcloudprofile

**Comment by oryagel** [comment]
Thanks!
I don't see the option of "Custom image name". I'm using TC 9.1.5 and version #0.5.156 of the plugin which is latest version with "deploy" tag.
Is there a newer compatible version of the plugin that I can use which include this option?

**Comment by paksv** [comment]
Unfortunately, no. You need to have TC 10.0 or higher which bundles VMware plugin.
