### ISSUE TITLE
Is there any plugins for intergrate with vRealize Orchestrator?

### ISSUE THREAD

**Issue by coolpalani** [JetBrains/teamcity-vmware-plugin#22]
Hello,

Is there any plugins for intergrate with vRealize Orchestrator and provision VMs from teamcity instead go with vCenter ?

**Comment by paksv** [comment]
Hi, I'm not aware of those. You can write up a build configuration that does such things for you. However, we don't use vRealize Orchestrator to prepare VM templates. PowerShell scripts + packer are enough in our case.
